
sudo: required
services:
  - docker
dist: trusty

language: python
python:
- '2.7'
- '3.6'

env:
  global:
    - BINTRAY_USER=ymagis
    - BINTRAY_ORG=ymagis
    - BINTRAY_REPO=Clairmeta
    - secure: "IKV4DSNedoMP/uTPWHVnJp2E/K9JDKu/InMJGQkQR5hreJGpWw6Q2OWo9qIDXQ0PXX9k5Aw3k+w+/Utp6+lNHUzMuKk92CCZ5ieolTgzYzaN/eYDIPVnQhE/S7v06liQn8f1IgDl+/brEmDmWQm73aYGjlkt1jBWma0ZOXxPC3eBhUMIc/5pWJXwnGRSNREW1LxLami+C7uN02qZwd1eHU+RU71bt5uYFHKrhMHB40MGQx20YpJ/yMcGhhXNZHSvmzKIus27oPreP1hFc22xO3Mfjq4Vgz9qoEQolJZPe/v2bHtMKooTPAfeTAI36oNpiTvR3SHEYX3uVjOIcuG3QCNPkhXEWIgjUtj3SVlM19Nvb0qtGkQVZnVXHtRZKKdzWbnOYI0zwWj3OEhyCzUbsadUFqiWJ7FZwtkYCT7Kmdi6UzPAh2L7/gSOECj4RZgZgpjaApJ3ruSMz/pMzDq1U+Q25esj/JS9vJU8eaSrOjD2Fk1RxhI8WXMZutb6dcLo0eQIrYo5LN7UOVRzd19KoliWMOmUQrTYlSU08CK0IVog4+rVlw8PjJ71LP/+w/5IZtCyhkYqmFSdwdNkQNKrydQE7jNZ6iZnkMmx9LLzwQ2HbamyjCQeoGHuK7SVlMXgkg0msqiyj5lpPnc5oZaTDCLJBUY9cDjxSYQDPOR7+/M="

install:
- pip install pipenv
- pipenv install --dev
- pipenv check

# This belong to default stage 'test'
script:
- pipenv run python -m compileall clairmeta
- nosetests --nocapture --with-doctest --doctest-options=+ELLIPSIS --with-coverage --cover-package=clairmeta --exclude='test_dcp_*' --exclude='test_mxf_*' --exclude='test_sequence*' --exclude='test_profile*' --exclude='test_cli*' --exclude='test_xml*'

# Stage conditions
stages:
  - name: test
    if: type IN (pull_request) OR tag =~ ^1
  - name: deploy
    if: tag =~ ^1
  - name: packaging
    if: tag =~ ^1

# Jobs
jobs:
  include:
  - stage: packaging
    script:
    - /bin/bash .travis/build_env.sh
  - stage: deploy
    script:
    - echo "Deploying..."
    - python setup.py sdist bdist_wheel
    deploy:
      - provider: releases
        skip_cleanup: true
        api_key:
          secure:     NnuZ3rpD3VgJ+E0SQvfkP23SWyml4z/QBWJMHbT1mnacS7QPHYmg4kU3NBjd4RCXAorwD/PRZoexcISZsyaok2h5ck/Y7nNkQzzE6m+qBSOb4G/ae1+La6X8KuvuxqvJb9t084lwHdmPfTCLE32dz3IYf1ZHmQJ3kKOV0tPK+GgBEEr/tgyKQ38ktCGEq5Fg52zfzOgiPWkmkp9PZjuZBf47FpXAUj8jrkcgFLJmWVek7qd9igDLcO7RVISTLWlpgc/OLKIyiiOfXywPZcGlN6zI3ynR8DpyQ0gV0wsVacAwxuLKpZ3Ill93wvclOhIMQdGfOhLyOV1UyC8ud/nBGh9ScaP7UR0gAsJqile3huRHgwV2tgXbkExUy2zpEo/jn7CbBMCh2Wt6TJSeQZolN6eimgs3Io0Jke+w6W29WCPzhntNpwWtI6KbK8s/VCH9pD5uSwTMBUeAPQpj/2XV6SDfgHZkP7m2qZeRFTxwr4Af9W6l7otwF8d2VdxCbpitMUwviQeZrWbaacevBXJlri+W/XH/vFxo1LHJeETYpg+663rlqApCt+UpMyBP3cd4pNzddCY2PUycjWuwu9SDtf180iK4Sj4gsllYm2D5xG1YmZnCqw5xzXthTgZ+MpbF/619dNLZQxfJDBMchj9wBNiFpHKOoJPerIHHqs132hA=
        file_glob: true
        file: dist/*
        on:
          branch: master
          tags: true
      - provider: pypi
        skip_cleanup: true
        user: ymagis
        password:
          secure: GVlzWA7XFERLLrq22aiOWM/+omejQXH4tVmaKjfXODnRSmtKN1JG2t4IqniNYstILpwv+CjOi4ANdAw2lLwZzbF17XIU2JlKya7R7jPuZOYh3f+98wrVzDyuAjflQIxcutoKX0ILGd+7JxvmmqzQNAoD6PCCnlE+WG11Mg+gK5Nmh9YE07fvLLerlCFFpEfSUEPsvWRgIkivPxbTkhUjQy5EiqgbQ9cmhW5ERoug+U1Q2r55RRyayfxpxPg+ASzi1Jn9NetAVFgkt1uaTEeU5NqjlEE1Z1+T9VRmpzpNlEXFWvkSA6iQMiSgDcEhJ6H49WORUv678/wJNmE/iYtENugABnMbmqTw58GYrHD2HI652JFuUstnbnh9Wp92GEgyLOQ3bNZJxkxi0h+onBxH8ubagg5d+Y5WjY4RQFthO1uxdFEJJtsuEgA0nNGVMrEjY6H/129KG4Sxtwws7jwPmamgd8UlVRc24QE4hJRYwfbtO/OgYl7Fr16+6rtaMLjG+CQ0GcCP5D29A8ChJG0n1P1PK1G9h/bUqaDX3Itk1vnqQkvQ+lEBQff9GmYDN5YKHZbOuJp9m7NLr8CkLR8FlgiZjz9TcRuNYVJo0vOwsDXfs65i3O2/z6FTRTL6eDFHZ4x7Am2eYguDWWDqNOTGaYnGhWQSxk7xhv8hjFcIwko=
        distributions: sdist bdist_wheel
        on:
          branch: master
          tags: true
          repo: Ymagis/ClairMeta